from .constant_reward import ConstantReward
from .damage_dealt_reward import DamageDealtReward
from .damage_taken_penalty import DamageTakenPenalty
from .team_damage_penalty import TeamDamagePenalty
from .ko_reward import KOReward
from .whiff_penalty import WhiffPenalty
from .combo_reward import ComboReward
from .velocity_reward import VelocityReward
from .grounded_penalty import GroundedPenalty
